# 当前工厂的二维化地图，指出工厂中存在的不可通过的点

config:
  width: 20
  height: 30

  block_count: 1
  point_count: 2
  machine_count: 2
  path_count: 2
  agv_count: 2

  blocks:
    - zone:
        id: 1
        zone: [1, 2, 10, 12]

  points:
    - point:
        id: 1
        coordinate: [8, 9]
    - point:
        id: 2
        coordinate: [12, 23]

  machines:
    - machine:
        id: 1
        type: packet_factory.Machine
        coordinate: [1, 2]
    - machine:
        id: 2
        type: packet_factory.Machine
        coordinate: [2, 3]

  paths:
    - path:
        id: 1
        type: bi
        begin: machine@1
        end: point@1
    - path:
        id: 2
        type: uni
        begin: machine@2
        end: point@2

  agvs:
    - agv:
        type: packet_factory.Agv
        coordinate: [1, 2]
        velocity: 10
        capacity: 12
    - agv:
        type: packet_factory.Agv
        coordinate: [2, 3]
        velocity: 1
        capacity: 12
