# 当前machine的基本配置,说明其坐标与基本的资源

config:
  jobs:
    - job:
        id: 0
        operations:
          - operation:
              id: 0
              machines:
                - { id: 0, time: 5 }
                - { id: 2, time: 4 }
          - operation:
              id: 1
              machines:
                - { id: 4, time: 3 }
                - { id: 2, time: 5 }
                - { id: 1, time: 1 }
          - operation:
              id: 2
              machines:
                - { id: 2, time: 4 }
                - { id: 5, time: 2 }
          - operation:
              id: 3
              machines:
                - { id: 5, time: 5 }
                - { id: 1, time: 6 }
                - { id: 0, time: 1 }
          - operation:
              id: 4
              machines:
                - { id: 2, time: 1 }
          - operation:
              id: 5
              machines:
                - { id: 5, time: 6 }
                - { id: 2, time: 6 }
                - { id: 3, time: 3 }

