# 当前工厂的二维化地图，指出工厂中存在的不可通过的点

config:
  width: 20  # todo
  height: 30  # todo

  blocks: # todo
    - zone:
        id: 1
        zone: [ 1, 2, 10, 12 ]

  points:
    - point:
        id: 1
        coordinate: [ 1, 0 ]
    - point:
        id: 2
        coordinate: [ 2, 0 ]
    - point:
        id: 3
        coordinate: [ 3, 0 ]
    - point:
        id: 4
        coordinate: [ 4, 0 ]
    - point:
        id: 5
        coordinate: [ 5, 0 ]


  machines: # todo: type, 根据数据集machine的id应从0开始编号
    - machine:
        id: 0
        type: packet_factory.Machine
        point_id: 1
    - machine:
        id: 1
        type: packet_factory.Machine
        point_id: 2
    - machine:
        id: 2
        type: packet_factory.Machine
        point_id: 3
    - machine:
        id: 3
        type: packet_factory.Machine
        point_id: 4
    - machine:
        id: 4
        type: packet_factory.Machine
        point_id: 5


  links:
    - link:
        id: 1
        begin: 1
        end: 2
    - link:
        id: 2
        begin: 2
        end: 3
    - link:
        id: 3
        begin: 3
        end: 4
    - link:
        id: 4
        begin: 4
        end: 5


  agvs: # todo: capacity
    - agv:
        id: 1
        type: packet_factory.Agv
        point_id: 2
        velocity: 1
        capacity: 42
    - agv:
        id: 2
        type: packet_factory.Agv
        point_id: 3
        velocity: 1
        capacity: 42
