config:
  env_type: simulation

  simulation:
    env_name: packet_factory

    agent:
      agent_name: packet_factory.RandomAgent
      name: 1
      id: 1

    factory_config:
      file: .config_set/map_config.yaml

    task_config:
      file: .config_set/job_config.yaml

    callback:
      # todo: args用字典形式传入
      map_callback:
        graph_loader:
          name: packet_factory_callback.MapLoader
          args: [/brandimarte/mk01.txt, /map_config.yaml]
        visualizer:
          name: packet_factory.Visualizer
          args: [3]    #  fps

      agent_callback:
        before_decision:
          name: base_callback.BeforeDecision
          args: []
        after_decision:
          name: base_callback.AfterDecision
          args: []