config:
  env_type: simulation
  default_time_quant: 0.1 # 为系统添加默认时间步

  simulation:
    env_name: packet_factory

    agent:
      agent_name: packet_factory.RandomAgent
      name: 1
      id: 1

    callback:
      map_callback:
        graph_loader:
          name: base_callback.NewMapLoader
          args: [ ]
        visualizer:
          name: backend_callback.Visualizer
          args: [ 3 ]    #  fps
        event_queue:
          name: base_callback.EventQueue
          args: [ ]
      agent_callback:
        before_decision:
          name: base_callback.BeforeDecision
          args: [ ]
        after_decision:
          name: base_callback.AfterDecision
          args: [ ]

