config:
  default_time_quant: 0.1
  env_type: simulation
  simulation:
    agent:
      agent_name: packet_factory.RandomAgent
      id: 1
      name: 1
    callback:
      agent_callback:
        after_decision:
          args: []
          name: base_callback.AfterDecision
        before_decision:
          args: []
          name: base_callback.BeforeDecision
      agv_callback:
        after_work:
          args: []
          name:
          - agv_callback.BaseCount
          - agv_callback.TransportCount
      job_callback:
        after_work:
          args: []
          name:
          - job_callback.BaseCount
          - job_callback.DelayCount
      machine_callback:
        after_work:
          args: []
          name:
          - machine_callback.BaseCount
          - machine_callback.ProcessCount
      map_callback:
        event_queue:
          args: []
          name: base_callback.EventQueue
        graph_loader:
          args: []
          name: base_callback.NewMapLoader
        visualizer:
          args:
          - 3
          name: backend_callback.Visualizer
    env_name: packet_factory
    event_config:
      file: D:\Project\finalPro\SkyEngine\backend\config_set\template_config_set\event_config.yaml
    factory_config:
      file: D:\Project\finalPro\SkyEngine\backend\config_set\template_config_set\map_config.yaml
    task_config:
      file: D:\Project\finalPro\SkyEngine\backend\config_set\template_config_set\job_config.yaml
