event_config:
  event_type: # 交给manager管理
    - packet_factory.JUST_TEST

    - packet_factory.ENV_PAUSED
    - packet_factory.ENV_RECOVER
    - packet_factory.ENV_RESTART

    - packet_factory.AGV_FAIL

    - packet_factory.MACHINE_FAIL

    - packet_factory.JOB_ADD

#  event_timeline: # 交给queue管理
#    - event:
#        timestamp: 1
#        type: packet_factory.JUST_TEST
#        args: ['trigger',{'data':233}]
#    - event:
#        timestamp: 2
#        type: packet_factory.MACHINE_FAIL
#        args: ['trigger',{'id': 1}]
#    - event:
#        timestamp: 3
#        type: packet_factory.JUST_TEST
#        args: ['recover',{'data':'agv failed.'}]
#    - event:
#        timestamp: 4
#        type: packet_factory.MACHINE_FAIL
#        args: [ 'recover',{'id': 1} ]

job_config:
  jobs:
    - job:
        id: 0
        operations:
          - operation:
              id: 0
              machines:
                - { id: 0, time: 5 }
          - operation:
              id: 1
              machines:
                - { id: 1, time: 3 }
          - operation:
              id: 2
              machines:
                - { id: 2, time: 4 }
          - operation:
              id: 3
              machines:
                - { id: 3, time: 6 }
          - operation:
              id: 4
              machines:
                - { id: 4, time: 7 }

map_config:
  width: 20  # todo
  height: 30  # todo

  points:
    - point:
        id: 1
        coordinate: [ 1, 0 ]
    - point:
        id: 2
        coordinate: [ 2, 0 ]
    - point:
        id: 3
        coordinate: [ 3, 0 ]
    - point:
        id: 4
        coordinate: [ 4, 0 ]
    - point:
        id: 5
        coordinate: [ 5, 0 ]


  machines: # todo: type, 根据数据集machine的id应从0开始编号
    - machine:
        id: 0
        type: packet_factory.Machine
        point_id: 1
    - machine:
        id: 1
        type: packet_factory.Machine
        point_id: 2
    - machine:
        id: 2
        type: packet_factory.Machine
        point_id: 3
    - machine:
        id: 3
        type: packet_factory.Machine
        point_id: 4
    - machine:
        id: 4
        type: packet_factory.Machine
        point_id: 5


  links:
    - link:
        id: 1
        begin: 1
        end: 2
    - link:
        id: 2
        begin: 2
        end: 3
    - link:
        id: 3
        begin: 3
        end: 4
    - link:
        id: 4
        begin: 4
        end: 5


  agvs: # todo: capacity
    - agv:
        id: 1
        type: packet_factory.Agv
        point_id: 2
        velocity: 1
        capacity: 42
    - agv:
        id: 2
        type: packet_factory.Agv
        point_id: 3
        velocity: 1
        capacity: 42

